### PR TITLE
Remove RIDK installation

### PR DESCRIPTION
**Pull request by CAMOBAP795**

### CODE REVIEW

**Comment by CAMOBAP795** [comment]
potentially will works once we will move out saas

cc @ronaldtse after this our installation will be much faster and clean

**Comment by ronaldtse** [comment]
@CAMOBAP795 thanks; build is still failing though.

**Comment by CAMOBAP795** [comment]
@ronaldtse yep( as far as I know we on the way to move out of `saas` dependency, (correct me if I'm wrong)

So I propose to keep this PR and once we will remove `saas` completely I will rerun tests again

**Comment by ronaldtse** [comment]
@CAMOBAP795 we are still using `libsass` (we use the `sassc` gem instead of `sass` gem). Are you expecting this PR to work when we drop compilation of `libsass`?

**Comment by ronaldtse** [comment]
I checked the failure log:

```
ERROR:  Error installing metanorma-cli:
14785	ERROR: Failed to build gem native extension.
14786
14787    current directory: C:/Tools/ruby25/lib/ruby/gems/2.5.0/gems/sassc-1.12.1/ext
14788C:/Tools/ruby25/bin/ruby.exe -rrubygems C:/Tools/ruby25/lib/ruby/gems/2.5.0/gems/rake-12.3.0/exe/rake RUBYARCHDIR=C:/Tools/ruby25/lib/ruby/gems/2.5.0/extensions/x64-mingw32/2.5.0/sassc-1.12.1 RUBYLIBDIR=C:/Tools/ruby25/lib/ruby/gems/2.5.0/extensions/x64-mingw32/2.5.0/sassc-1.12.1
14789cd libsass
14790make lib/libsass.so
14791mkdir lib
14792cc -Wall -O2 -I C:/Tools/ruby25/lib/ruby/gems/2.5.0/gems/sassc-1.12.1/ext/libsass/include -c -o src/cencode.o src/cencode.c
14793process_begin: CreateProcess(NULL, cc -Wall -O2 -I C:/Tools/ruby25/lib/ruby/gems/2.5.0/gems/sassc-1.12.1/ext/libsass/include -c -o src/cencode.o src/cencode.c, ...) failed.
14794make (e=2): The system cannot find the file specified.
14795
```

It's failing on `sassc` which requires `libsass`. Chocolatey's `sass` package installs "dart-sass", which we can't use in Ruby.

Maybe the best choice is actually falling back to Ruby `sass` which doesn't require any compilation!

**Comment by CAMOBAP795** [comment]
@ronaldtse thanks for clarification I was confused by https://sass-lang.com/ruby-sass :

```
Ruby Sass was the original implementation of Sass, but it reached its end of life as of 26 March 2019. It's no longer supported, and Ruby Sass users should migrate to another implementation.
```

But looks like ruby-saas different then sassc

**Comment by ronaldtse** [comment]
`ruby-sass` is in pure Ruby.
`sassc` requires `libsass` which is in C++.
`dart-sass` is in Dart JS.

Ruby Sass is deprecated but it is still fine for our usage. If using it allows us not to compile anything, I'd rather fall back to it.

**Comment by CAMOBAP795** [comment]
@ronaldtse I propose better to report ticket to https://github.com/sass/sassc-ruby so they will include binaries in gem (like nokogiri do)

**Comment by ronaldtse** [comment]
@CAMOBAP795 that is a big IF. You can always propose a ticket, but we should not be basing our decisions on what they may or may not do.

**Comment by ronaldtse** [comment]
It would be much *much* easier to just use ruby-sass.

**Comment by CAMOBAP795** [comment]
> @CAMOBAP795 that is a big IF. You can always propose a ticket, but we should not be basing our decisions on what they may or may not do.

For sure but till this, we can continue to use RIDK and compile `libsass` during gem installation (like we do right now and before)

The main idea behind getting out of RIDK is to really have the possibility to install metanorma in a single command like this `cinst metanorma -y`

**Comment by ronaldtse** [comment]
And we can achieve this if we just use ruby-sass.

**Comment by CAMOBAP795** [comment]
> And we can achieve this if we just use ruby-sass.

Yes, this also solution, finally it's up to you, but I think better get out of unsupported components

**Comment by CAMOBAP795** [comment]
According to sass/sassc-ruby#126 will be added to the next release, so I will keep this PR

cc @ronaldtse

**Comment by ronaldtse** [comment]
@CAMOBAP795 any updates here? Thanks.

**Comment by CAMOBAP795** [comment]
@ronaldtse `sassc` now comes with prebuilt, I started one more build to check

**Comment by CAMOBAP795** [comment]
Not ready because `ruby_deep_clone`, https://github.com/gmodarelli/ruby-deepclone/issues/16 - reported

**Comment by ronaldtse** [comment]
@CAMOBAP795 do we still use `ruby_deep_clone` ? Can we replace it?

**Comment by ronaldtse** [comment]
ping @CAMOBAP795

**Comment by CAMOBAP795** [comment]
> do we still use ruby_deep_clone ? 

Yep https://github.com/relaton/relaton-iso-bib/blob/master/relaton_iso_bib.gemspec#L40

> Can we replace it?

Good question, IDK this dependency was there from the beginning.

But let's imagine that we can replace it

Let me list pros/cons here again:

Pros:
 - the installation will be much faster and simpler if we will not build native extensions on the client's side 

Cons:
 - we will not able to use other gems which haven't a pre-builts 

@ronaldtse how do you think?

**Comment by ronaldtse** [comment]
Ping @andrew2net -- can we remove the `ruby_deep_clone` gem from this single line of usage?

https://github.com/relaton/relaton-iso-bib/blob/1d2401dd3a3127bfaa11d443132212e532d85d73/lib/relaton_iso_bib/iso_bibliographic_item.rb#L173

Once it's done we can remove RIDK from Windows install. Thanks!

**Comment by andrew2net** [comment]
@ronaldtse if we remove `ruby_deep_clone` gem then we have to implement `RelatonIsoBib#clone` method which clones all the properties and properties of the properties. I don't remember exactly but think we use the gem in other places.

**Comment by ronaldtse** [comment]
@andrew2net I think there is an issue with the behavior of `to_all_parts`. Typical convention says that `to_*` gives you a new object that does not modify the original. The expectation of `isobib.to_all_parts` is to give a new IsoBib item that is "all parts".

Instead of deep clone, can we create a new bib item that is "all parts"? This way we can get rid of the ruby deep clone gem. (similarly, the `to_most_recent_reference` method) Thanks!

**Comment by CAMOBAP795** [comment]
Works now (because currently, all gems have native libraries for windows)

But this may change in future, so I'm a bit worried to merge this 

@ronaldtse let me know if you changed you mind, if not I will merge it

**Comment by ronaldtse** [comment]
@CAMOBAP795 I think this is great news! Let's merge this. If we need RIDK in the future for some specific platform, maybe it should go into a separate Chocolatey package (e.g. metanorma.x86)

**Pull request merged**
