### PR TITLE
Release 1.1.7

### PR DESCRIPTION
**Pull request by CAMOBAP795**
- https://github.com/metanorma/chocolatey-metanorma/issues/23

### CODE REVIEW

**Comment by ronaldtse** [comment]
@CAMOBAP795 AppVeyor failed... Can we make sure we get this published to Chocolatey before next Sunday? We have a client that needs it. Thanks!

**Comment by CAMOBAP795** [comment]
@ronaldtse I think it will be resolved today there is some issue with third-party package install (core utilities)

**Comment by CAMOBAP795** [comment]
@ronaldtse ready for review & merge

**Comment by ronaldtse** [comment]
Thanks!

**Pull request merged**
