### PR TITLE
Move to packed-mn from metanorma-cli gem

### PR DESCRIPTION
**Pull request by CAMOBAP**
- #49

### CODE REVIEW

**Comment by ronaldtse** [comment]
Test failed:

```
Run call RefreshEnv.cmd
7
Refreshing environment variables from registry for cmd.exe. Please wait...Finished..
8
C:\hostedtoolcache\windows\Python\3.7.9\x64\Scripts\xml2rfc.exe
9
C:\Strawberry\perl\site\bin\latexmlmath
10
C:\Strawberry\perl\site\bin\latexmlmath.bat
11
INFO: Could not find files for the given pattern(s).
```

**Review by ronaldtse — APPROVED** [review]
LGTM please merge when ready. Thanks!

**Comment by CAMOBAP** [comment]
Tests failed for mn-samples-un, https://github.com/metanorma/mn2pdf/issues/46 reported

**Comment by ronaldtse** [comment]
All passing, can we merge @camobap?

**Comment by CAMOBAP** [comment]
@ronaldtse yep

**Pull request merged**
