### PR TITLE
Avoid hardcoded version in path of upload-artifact

### PR DESCRIPTION
**Pull request by CAMOBAP795**

### CODE REVIEW

**Comment by ronaldtse** [comment]
Look forward having this fixed!

**Comment by CAMOBAP795** [comment]
@ronaldtse could you please add `CHOCO_API_KEY` to `secrets` for this repo & https://github.com/metanorma/chocolatey-latexml

**Comment by CAMOBAP795** [comment]
I see that we have it for latexml, https://github.com/metanorma/chocolatey-latexml/issues/11 was done

@ronaldtse can you confirm that secrets.CHOCOLATEY_API_KEY exists for this repo?

**Comment by ronaldtse** [comment]
@CAMOBAP795 yup it is in this repo too. I see the package has been submitted and published. Thanks!

**Pull request merged**
