### PR TITLE
Add xml2rfc tools

### PR DESCRIPTION
**Pull request by CAMOBAP795**
- https://github.com/metanorma/metanorma-linux-setup/issues/10

### CODE REVIEW

**Comment by ronaldtse** [comment]
@CAMOBAP795 can you also add it to the homebrew-metanorma formula? Thanks!

**Comment by CAMOBAP795** [comment]
```
ValueError: path '/usr/local/share/man/man1' cannot be absolute
    ----------------------------------------
```

`id2xml` not ready to be installed on windows I looking to a bugtracker to report this issue

**Comment by ronaldtse** [comment]
Why do we use `id2xml` ?

**Comment by CAMOBAP795** [comment]
@ronaldtse transitive dependency from `idnits`

**Comment by CAMOBAP795** [comment]
Because of 

```
   Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\appveyor\appdata\local\temp\1\chocolatey\pip-install-fcss0o\id2xml\setup.py", line 165, in <module>
        zip_safe = False,
      File "C:\Python27\lib\site-packages\setuptools\__init__.py", line 143, in setup
        return distutils.core.setup(**attrs)
      File "C:\Python27\lib\distutils\core.py", line 151, in setup
        dist.run_commands()
      File "C:\Python27\lib\distutils\dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "C:\Python27\lib\distutils\dist.py", line 972, in run_command
        cmd_obj.run()
      File "C:\Python27\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "C:\Python27\lib\distutils\command\install.py", line 575, in run
        self.run_command(cmd_name)
      File "C:\Python27\lib\distutils\cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "C:\Python27\lib\distutils\dist.py", line 972, in run_command
        cmd_obj.run()
      File "C:\Python27\lib\distutils\command\install_data.py", line 58, in run
        dir = convert_path(f[0])
      File "C:\Python27\lib\distutils\util.py", line 124, in convert_path
        raise ValueError, "path '%s' cannot be absolute" % pathname
    ValueError: path '/usr/local/share/man/man1' cannot be absolute
    ----------------------------------------
```

`idnits` cannot be installed on windows, this issue already fixed in SVN https://trac.tools.ietf.org/tools/ietfdb/browser/branch/elft/id2xml/setup.py?rev=16232

I didn't find a way to register on https://trac.tools.ietf.org so I send an email to them

**Comment by ronaldtse** [comment]
@CAMOBAP795 then let's not install `idnits` on Windows. It's not strictly required by Metanorma.

**Comment by CAMOBAP795** [comment]
@ronaldtse ok it works I will create separate ticket for `idnits`

**Pull request merged**
